version: '3.5'

services:
    api-postgres:
        container_name: api_postgres_container
        image: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5433:5432"
        networks:
            - api-postgres
        restart: unless-stopped

    api-pgadmin:
        container_name: api_pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - api-postgres
        restart: unless-stopped

networks:
    api-postgres: 
        driver: bridge

volumes:
    postgres:
    pgadmin:
